import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Board } from '../../components/Board'
import { GamePlay } from '../../components/Gameplay'
import { Man } from '../../components/Man'
import { Player as PlayerView} from '../../components/Player'
import { createMap,MapData} from "../../model/mapData"
import { PlayerModel } from '../../model/player'

const Home: NextPage<{map:MapData,players:PlayerModel[]}> = ({map,players}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GamePlay map={map} players={players}></GamePlay>
    </div>
  )
}

export default Home

export const getServerSideProps : GetServerSideProps  = async () => {
  return {
    props :{
      map: createMap(),
      players: [
        {
          id:0,
          x:1,
          y:10
        },
        {
          id:1,
          x:4,
          y:7
        }
      ]
    }
  }
}
