import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { GamePlay } from '../../components/Gameplay'
import { createMap,MapData} from "../../model/mapData"
import { ManModel } from '../../model/player'

const Home: NextPage<{map:MapData,players:ManModel[]}> = ({map,players}) => {
  return (
    <div>
      <Head>
        <title>Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GamePlay 
        players={[
          {meta:{displayName:"fuga",code:0,you:false}},
          {meta:{displayName:"hoge",code:1,you:true}},
          {meta:{displayName:"piyo",code:2,you:false}},
          {meta:{displayName:"hage",code:3,you:false}},
        ]} 
        status="Playing" map={map} men={players}></GamePlay>
    </div>
  )
}

export default Home

export const getServerSideProps : GetServerSideProps  = async () => {
  return {
    props :{
      map: createMap(),
      players: [
        {
          id:0,
          x:1,
          y:10
        },
        {
          id:1,
          x:4,
          y:7
        }
      ]
    }
  }
}
