import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Board } from '../components/Board'
import { createMap,MapData} from "../model/mapData"

const Home: NextPage<{map:MapData}> = ({map}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Board mapData={map}></Board>
      </main>

    </div>
  )
}

export default Home


export const getServerSideProps : GetServerSideProps  = async () => {
  return {
    props :{
      map: createMap()
    }
  }
}
