import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Board } from '../components/Board'
import { Man } from '../components/Man'
import { createMap,MapData} from "../model/mapData"
import { Player } from '../model/player'
import styles from "./index.module.css"

const Home: NextPage<{map:MapData,players:Player[]}> = ({map,players}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Board mapData={map}></Board>
        <div>
        {
        players.map(p => <Man key={p.id} x={p.x} y={p.y} player={p.id}></Man>)
        }
        </div>
        
      </main>
    </div>
  )
}

export default Home

export const getServerSideProps : GetServerSideProps  = async () => {
  return {
    props :{
      map: createMap(),
      players: [
        {
          id:0,
          x:1,
          y:10
        },
        {
          id:1,
          x:4,
          y:7
        }
      ]
    }
  }
}
